tap "blender/tap"
tap "github/gh"
tap "go-task/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "hpedrorodrigues/tools"
tap "microsoft/git"
tap "tmspzz/tap"
brew "ansible"
brew "autoconf"
brew "openssl@3"
brew "asdf"
brew "autojump"
brew "python@3.10"
brew "azure-cli"
brew "bash-completion"
brew "caddy"
brew "carthage"
brew "cowsay"
brew "openldap"
brew "zstd"
brew "curl"
brew "direnv"
brew "doxygen"
brew "fzf"
brew "gh"
brew "gifsicle"
brew "git"
brew "git-lfs"
brew "gitleaks"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "helm"
brew "httpie"
brew "iperf"
brew "jq"
brew "kubectx"
brew "mosh"
brew "nmap"
brew "parallel"
brew "pv"
brew "python@3.9"
brew "rbenv"
brew "ssh-copy-id"
brew "starship"
brew "swiftlint"
brew "telnet"
brew "terraform"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "vim"
brew "wget"
brew "wrk"
brew "yarn"
brew "yq"
brew "zplug"
brew "go-task/tap/go-task"
brew "tmspzz/tap/rome"
cask "1password"
cask "alfred", args: { appdir: "/Applications" }
cask "android-studio"
cask "anki", args: { appdir: "/Applications" }
cask "brave-browser", args: { appdir: "/Applications" }
cask "caffeine", args: { appdir: "/Applications" }
cask "charles", args: { appdir: "/Applications" }
cask "chromedriver", args: { appdir: "/Applications" }
cask "dash", args: { appdir: "/Applications" }
cask "docker", args: { appdir: "/Applications" }
cask "dockutil"
cask "font-jetbrains-mono", args: { appdir: "/Applications" }
cask "git-credential-manager-core"
cask "google-cloud-sdk", args: { appdir: "/Applications" }
cask "graphql-playground", args: { appdir: "/Applications" }
cask "licecap", args: { appdir: "/Applications" }
cask "ngrok", args: { appdir: "/Applications" }
cask "notion", args: { appdir: "/Applications" }
cask "obsidian", args: { appdir: "/Applications" }
cask "scroll-reverser", args: { appdir: "/Applications" }
cask "sequel-ace", args: { appdir: "/Applications" }
cask "slack", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "textexpander", args: { appdir: "/Applications" }
cask "the-unarchiver", args: { appdir: "/Applications" }
cask "todoist"
cask "transmit", args: { appdir: "/Applications" }
cask "tunnelblick", args: { appdir: "/Applications" }
cask "viber", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "warp"
vscode "apollographql.vscode-apollo"
vscode "CodeSandbox-io.codesandbox-projects"
vscode "cweijan.vscode-mysql-client2"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "fabiospampinato.vscode-diff"
vscode "GitHub.codespaces"
vscode "GitHub.copilot"
vscode "GitHub.copilot-labs"
vscode "GitHub.vscode-pull-request-github"
vscode "gitpod.gitpod-desktop"
vscode "golang.go"
vscode "GraphQL.vscode-graphql"
vscode "GraphQL.vscode-graphql-syntax"
vscode "hashicorp.terraform"
vscode "jdinhlife.gruvbox"
vscode "jumpinjackie.vscode-map-preview"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "redhat.vscode-yaml"
vscode "sainnhe.gruvbox-material"
vscode "shanoor.vscode-nginx"
vscode "unifiedjs.vscode-mdx"
vscode "zxh404.vscode-proto3"
